name: garage
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  args: ^2.0.0
  content_length_validator: ^1.1.0
  shelf: ^1.1.0
  shelf_helmet: ^1.1.0
  shelf_hotreload: ^1.4.0
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.0.0
  supabase: ^1.6.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0

  # password
# XqYZwYJyrVohdbaK